main:
  label: 'IdM'
  host: '<LDAP_HOST_IP_HERE>'
  port: 389
  uid: 'uid'
  method: 'tls'
  bind_dn: 'uid=admin,cn=users,cn=accounts,dc=us-gov-west-1,dc=compute,dc=internal'
  password: '<LDAP_ADMIN_PASSWORD_HERE>'
  encryption: 'plain'
  base: 'cn=accounts,dc=us-gov-west-1,dc=compute,dc=internal'
  verify_certificates: false
  attributes:
    username: ['uid']
    email: ['mail']
    name: 'displayName'
    first_name: 'givenName'
    last_name: 'sn'
